# Generated by Django 3.2.12 on 2024-05-02 05:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gn_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gn_user',
            name='id',
        ),
        migrations.AddField(
            model_name='gn_user',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
