# Generated by Django 3.2.12 on 2024-05-03 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20240502_0500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gn_universite',
            fields=[
                ('uni_id', models.AutoField(primary_key=True, serialize=False)),
                ('uni_name', models.CharField(max_length=100)),
                ('uni_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='gn_admin',
            name='id',
        ),
        migrations.AddField(
            model_name='gn_admin',
            name='adminid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Gn_Fakulte',
            fields=[
                ('fakulte_id', models.AutoField(primary_key=True, serialize=False)),
                ('fakulte_name', models.CharField(max_length=64)),
                ('fakulte_uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gn_universite')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('video_url', models.URLField(blank=True, null=True)),
                ('fakulte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gn_fakulte')),
            ],
        ),
    ]
