# Generated by Django 3.2.12 on 2024-05-03 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20240503_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='fakulte',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gn_admin',
            name='adminid',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gn_fakulte',
            name='fakulte_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gn_universite',
            name='uni_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Gn_Bolum',
            fields=[
                ('bolum_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('bolum_name', models.CharField(max_length=100)),
                ('bolum_fakulte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gn_fakulte')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='bolum',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.gn_bolum'),
        ),
    ]
