# Generated by Django 3.2.12 on 2024-05-03 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240503_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bolum',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.gn_bolum'),
        ),
    ]
