# Generated by Django 3.2.12 on 2024-05-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_course_bolum'),
    ]

    operations = [
        migrations.AddField(
            model_name='gn_universite',
            name='uni_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uni_logo/'),
        ),
    ]
