# Generated by Django 3.2.12 on 2024-05-03 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gn_universite_uni_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.gn_bolum'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gn_admin',
            name='adminid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gn_bolum',
            name='bolum_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gn_fakulte',
            name='fakulte_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='gn_universite',
            name='uni_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
